-- ============================================================
-- E-Commerce Exploratory Data Analysis (EDA)
-- Tool: PostgreSQL (pgAdmin 4)
-- Database: ecommerce_db
-- Role framing: Junior Data Analyst
-- ============================================================

-- 1. Number of customers in each city, and the top 3 cities by customer count.

-- Customers per city
SELECT city,
        COUNT(customer_name) AS count_customer
FROM customers
GROUP BY city
ORDER BY count_customer DESC;

-- Top 3 cities
SELECT city,
        COUNT(*) AS count_customer
FROM customers
GROUP BY city
ORDER BY count_customer DESC
LIMIT 3;

-- 2. Total revenue generated by each city, ranked highest to lowest.
SELECT delivery_city,
    SUM(o.total_amount) AS total_revenue
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
WHERE delivery_city IS NOT NULL
GROUP BY delivery_city
ORDER BY total_revenue DESC;

-- 3. Total revenue and total orders for each product; identify the best-performing product.
SELECT product_name,
        COUNT(order_id) AS total_orders,
        SUM(total_amount) AS total_revenue
FROM orders
GROUP BY product_name
ORDER BY total_revenue DESC;

-- 4. Average order value for each city; which city has the highest average order value?
SELECT delivery_city,
        AVG(o.total_amount) AS avg_order_value
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
WHERE c.delivery_city IS NOT NULL
GROUP BY c.delivery_city
ORDER BY avg_order_value DESC;

-- 5. Number of orders and total revenue by payment method; which contributes most revenue?
SELECT payment_method,
        COUNT(order_id) AS total_orders,
        SUM(total_amount) AS total_revenue
FROM orders
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- 6. Number of customers who signed up each year.
SELECT
    EXTRACT(YEAR FROM signup_date) AS signup_year,
        COUNT(customer_id) AS total_customers
FROM customers
GROUP BY signup_year
ORDER BY signup_year DESC;
